sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2

install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  # - export PATH="$HOME/pandoc:$PATH"
  # - mkdir $HOME/pandoc
  # - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  # - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
  #     -d $HOME/pandoc
  # - chmod +x $HOME/pandoc/pandoc
  # - pandoc --version

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet --trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: wkG/bf9LoT5Fp0kowsMp3mXLx2/kZ7MGPEeL5UjHdQC3i3hnRynQ+4Ev4YL5nvIW0gtDDumm+AwsxjMFjJNW4U5b58fz2PDz8YSVFbtVHGNu0NOpRsRwQMa07hcls2uMFZL/zz6TbabuTZ6thd+S2WMQ5ONCdgP6b47V2xOnijUcRUQUGal70dO30O+fjjR4dSa02I94N+hzGMo/5YZF7Q/65s5t28aVxk4zIyTveQeRqR6/+OFCVMmXhQMoilEBvkPUqAfklOVsEcmswjZONaLEA0poqB9wrLybbSskgUDf3YMN+0O5887FWpu6HcudY41TKXwvBpAKt3e3kzF6UuqdmjpQvsovkIGiAIXb9U94WDgxTi8cWM5Pgxp5Ckr5ItL2Uo8ybLE+l2sSJEwnddtJhgbAZGc44iPMd7q51Xs+QrU7cA0RQQN59rUh8321d8kA4XZn6wtpr8KjQhYvV0IoEFK+3nyqJ2+FUvrdGAnncQl5zWmPYPGp5H2VSFq44VAqqg3/amjBt5jqAZPd2NOVyflaEUuMFgfhGX2S/GB5uYAXFlJMvmOSVeUiGfrtjHqETjc2OTG1V7jT0pIjkgEcNzzvK8If5Tr0yZi13El5ONkDArVVSR4ACG2xZoNVnbfqOATfPcsnTv4p1bDox02r00ABB3UgDQaBOYq71eY=

branches:
  only:
    - source