
# Jykell configuration
name             : elsewhere
title            : elsewhere
description      : 一个辅助记忆的树洞
language         : zh-CN
image            : true
safe             : false
timezone         : Asia/Shanghai
source           : "."
destination      : "./_site"
excerpt_separator: "<!--more-->"
url              : "https://devylee.github.io"

collections  : 
  posts      : 
    output   : true
    permalink: "/post/:year/:month/:title.html"
  pages      : 
    output   : true
    permalink: "/:name/index.html"
  uploads    : 
    output   : true

# Pagination
paginate     : 5
paginate_path: "/page/:num/"

# Conversion
lsi        : false
highlighter: rouge 
kramdown:
  input             : GFM
  parse_block_html  : true
  parse_span_html   : true
  html_to_native    : true
  syntax_highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions:
#    - footnotes

# Widget
google_analytics : UA-92777218-1
disqus           : devylee
twitter_card_site: "@idevylee"

# Settings for deploy rake task
ghusername: devylee
repo    : "devylee.github.io"
branch  : source

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-feed

exclude:
  - vendor
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.Rmd"
  - ".travis.yml"
