---
title: Devylee.Github.Io
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
language: zh-CN
safe: false
source: "."
destination: "./_site"
excerpt_separator: "<!--more-->"
lsi: false
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  html_to_native: true
  syntax_highlighter: rouge
url: https://devylee.github.io
paginate: 5
paginate_path: "/page/:num/"
permalink: "/post/:year/:month/:title.html"
name: elsewhere
description: 一个辅助记忆的树洞
image: true
author: Devy
nickname: devy
bio: 代码猴' 全栈' 真爱LNMP' 勾搭着一众开发技术' 拖延症患者' 已婚俩孩儿带只狗'
location: Dalian, China
twitter_username: idevylee
github_username: devylee
weibo_username: devylee
google_analytics: UA-92777218-1
disqus: devylee
repo: devylee.github.io
branch: source
gems:
- jekyll-paginate
- jekyll-sitemap
exclude:
- vendor
- Rakefile
- Gemfile
- Gemfile.lock
- "*.Rmd"
- ".travis.yml"
