
# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'zh-cn'

# Website info
name: elsewhere
description: '一个辅助记忆的树洞.'
image: true

# Author's info
twitter_username: idevylee
github_username:  devylee
author: Devy
nickname: devy
bio: "代码猴' 全栈' 真爱LNMP' 勾搭着一众开发技术' 拖延症患者' 已婚俩孩儿带只狗'"
location: 'Dalian, China'

#google_analytics: 
#disqus: 
baseurl: /

# Permalinks
permalink: /:title/

# Settings for deploy rake task
safe: false
lsi: false
repo: 'devylee.github.io'
destination: '../gh-pages/'

# gems and other configs
gems: [jekyll-paginate]

exclude:
  - vendor
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.Rmd"
  - vendor
  - .travis.yml