
# Jykell configuration
language: 'zh-cn'
timezone: 'Asia/Shanghai'
highlighter: rouge 
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  html_to_native: true
  syntax_highlighter: rouge

# Pagination
paginate: 5
paginate_path: '/p/:num/'

#markdown: redcarpet
#redcarpet:
#  extensions:
#    - footnotes

# Website info
name: elsewhere
description: '一个辅助记忆的树洞'
image: true

# Author's info
twitter_username: idevylee
github_username:  devylee
author: Devy
nickname: devy
bio: "代码猴' 全栈' 真爱LNMP' 勾搭着一众开发技术' 拖延症患者' 已婚俩孩儿带只狗'"
location: 'Dalian, China'

google_analytics: 'UA-92777218-1'
disqus: devylee
disqus_url: 'https://devylee.github.io'
baseurl: /

# Permalinks
permalink: '/:year/:month/:title.html'

# Settings for deploy rake task
safe: false
lsi: false
repo: 'devylee.github.io'
branch: source
destination: _site

# gems and other configs
gems: [jekyll-paginate]

exclude:
  - vendor
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.Rmd"
  - .travis.yml